### ISSUE TITLE
Rewrite environment.yml to fix package versions

### ISSUE THREAD

**Issue by smithara** [MagGeo/MagGeo-Annotation-Program#2]
The file should be rewritten to fix the MAJOR.MINOR package versions (e.g. like https://github.com/smithara/containers/blob/main/conda-envs/jupyter-scipy.yml), according to a recently created environment that the notebooks have been tested against. That will let people recreate the old environment in a mostly deterministic way, enabling computational reproducibility. (even when the repository is not maintained to bring compatibility with newer package versions, doing that will at least give the instruction of what package versions were originally used)

**Comment by mfbenitezp** [comment]
Thanks @smithara this as been addressed in https://github.com/MagGeo/MagGeo-Annotation-Program/tree/minconda_version after some testing I will merge into the master
