### ISSUE TITLE
Adjust notebooks to run in unattended mode

### ISSUE THREAD

**Issue by smithara** [MagGeo/MagGeo-Annotation-Program#3]
To enable automatic testing (e.g. updating the conda environment and running the notebooks automatically against the new environment for a basic test of compatibility), the notebooks should be adjusted so that they can be executed from top to bottom without manually specifying input every time.

**Comment by mfbenitezp** [comment]
Thanks @smithara in this new branch I have address this suggestion. You will find a MagGeo_main_py that can be run in unattended mode if users provide the VirES token. I will also later add the parallel mode as part of the parameters, at the moment is sequential.  https://github.com/MagGeo/MagGeo-Annotation-Program/tree/minconda_version

**Comment by mfbenitezp** [comment]
I'd say this issues is being address in the new update. The only part I could not make unattended in the notebooks was the token entry.

**Comment by smithara** [comment]
A hint in case you want to set up an automated test in the future on GitHub Actions:

You can set the token beforehand with the CLI instruction:
```
viresclient set_token https://vires.services/ows ${{ secrets.VIRES_TOKEN }}
```
(having set `VIRES_TOKEN` as a secret on the repository)

If you then have the notebook without any token entry step, then it will be able to use that preconfigured one in the automated test, but a user will be prompted to enter one if they haven't set one up before. It' probably not worth the hassle to set up the automation now, but something to consider in the future!

**Comment by mfbenitezp** [comment]
Thanks @smithara for the suggestion!! I think I will try that in the next version where I plan to make other changes to the MagGeoFunctions, and the main script to run the parallel mode using the shell and the parameters file.
